# Use the official Node.js image
FROM node:23.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package.json package-lock.json . 

# Install dependencies (no need for build tools as we're using bcryptjs)
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port that the application will run on
EXPOSE 5173

# Command to start the application
CMD ["npm", "run", "dev"]